apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: servicecreator-rb
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: servicecreator-role
subjects:
  - kind: ServiceAccount
    name: servicecreator-sa
    namespace: default
